---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r,include=FALSE}
library(tidyverse)
library(kableExtra)

# Importing Data from Qualtrics 
temp <- read.csv("Data/qualtrics_pilot_data.csv", header=FALSE, na.strings="")

x <- temp[2,] # Takes row 2 and places it into an object
data <- temp[-c(1:3),] # Remove row 1 to 2
colnames(data) <- x # turn row 2 from line 5 into header of dataframe

num <- nrow(data) # Tells us how many participants we have in our dataset

data$Cond1 <- rowSums(is.na(data[18:53])) # counts how many na's occur between columns 18 to 53
data$Cond2 <- rowSums(is.na(data[54:89]))
data$Cond3 <- rowSums(is.na(data[90:125]))
data$Cond4 <- rowSums(is.na(data[126:161]))

# Determing what is the condition, if they have less than 36 NA, then that is there condition
data$Condition[data$Cond1 < 36] <- 1
data$Condition[data$Cond2 < 36] <- 2
data$Condition[data$Cond3 < 36] <- 3
data$Condition[data$Cond4 < 36] <- 4

# Splitting the Conditions
cond1 <- data[ which(data$Condition==1), ]
cond2 <- data[ which(data$Condition==2), ]
cond3 <- data[ which(data$Condition==3), ]
cond4 <- data[ which(data$Condition==4), ]

cond1.red <- cond1[,c(6, 18:53, 162:165, 171)]  ## using Cond1 ordering
cond2.red <- cond2[,c(6, 62:65, 70:73, 82:85, 58:61, 74:77, 86:89, 66:69, 78:81, 54:57, 162:165, 171)]
cond3.red <- cond3[,c(6, 94:97, 106:109, 118:121, 98:101, 110:113, 122:125, 102:105, 114:117, 90:93, 162:165, 171)]
cond4.red <- cond4[,c(6, 138:161, 130:137, 126:129, 162:165, 171)]

## Getting rid of condition markers so rbind will work
names(cond1.red) = gsub(pattern = "C*.* - ", replacement = "", x = names(cond1.red))     
names(cond2.red) = gsub(pattern = "C*.* - ", replacement = "", x = names(cond2.red))  
names(cond3.red) = gsub(pattern = "C*.* - ", replacement = "", x = names(cond3.red))  
names(cond4.red) = gsub(pattern = "C*.* - ", replacement = "", x = names(cond4.red))  

together <- rbind(cond1.red, cond2.red, cond3.red, cond4.red)

i <- c(1:37)
together[ , i] <- apply(together[ , i], 2,            # Specify own function within apply
                        function(x) as.numeric(as.character(x)))

#write.csv(together, "together.csv")

################## Recoding items #########################
together$`Most days, I feel happiest when the workday is soon to be complete.` <- 7 - together$`Most days, I feel happiest when the workday is soon to be complete.`
together$`This job drains my energy.` <- 7 - together$`This job drains my energy.`

## BEHAVIORAL (NONE):

## COGNITIVE: 

together$`Thinking about work saps my energy.` <- 7 - together$`Thinking about work saps my energy.`
together$`I often think about finding another job.` <- 7 - together$`I often think about finding another job.`
```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.
```{r, include=FALSE}
alpha_reduction2<-psych::alpha(together[,c(2,5,6,7,10,13,14,15,19,20,22,23,26,29,31,33,34,36)]) #alpha-.90

Reduction_2Items<-together[,c(2,5,6,7,10,13,14,15,19,20,22,23,26,29,31,33,34,36)]

Reduction_2Items<-Reduction_2Items%>%rename(
  Item_1=`I’m able to concentrate on my work without distractions.`,
 # Item_2=`I have a hard time detaching mentally from my work.`,
  Item_3=`Time passes quickly while I’m working.`,
 # Item_4=`I find it difficult to mentally disconnect from work.`,
  Item_5=`I enjoy thinking about work even when I’m not at work.`,
 # Item_6=`Most days, I feel happiest when the workday is soon to be complete.`,
 # Item_7=`I am happiest when I am immersed in a project.`,
  Item_8=`I love starting my workday.`,
  Item_9=`I devote more time than is expected of me.`,
  Item_10=`I have to be reminded to take breaks while I’m at work.`,
 # Item_11=`I never miss a work deadline.`,
 # Item_12=`I never allow distractions to interfere with my work.`,
  Item_13=`I devote my full attention to my work tasks throughout the day.`,
 # Item_14=`Thinking about work saps my energy.`,
 # Item_15=`I would rather direct my focus toward a work task than a personal task.`,
  Item_16=`I’m able to maintain good levels of energy throughout the workday.`,
  Item_17=`I enjoy spending time completing my job tasks.`,
  Item_18=`Most days I feel enthusiastic about starting my work day.`,
 # Item_19=`I feel motivated to go beyond what is asked of me.`,
 # Item_20=`This job drains my energy.`,
 # Item_21=`When work is slow I find ways to be productive.`,
  Item_22=`I express enthusiasm for my job while at work.`,
  Item_23=`I try my best to perform well at work.`,
 # Item_24=`If I notice my energy level is low, I take corrective steps to re-energize.`,
 # Item_25=`I plan my future with this company.`,
  Item_26=`I believe this company cares about my career goals.`,
 # Item_27=`I often think about finding another job.`,
  Item_28=`This organization challenges me to work at my full potential.`,
  Item_29=`I am proud to be a member of this organization.`,
 # Item_30=`I feel supported by my supervisor when I fail at a task.`,
 # Item_31=`I feel proud of my accomplishments within this organization.`,
  Item_32=`My job makes me feel like I’m part of something meaningful.`,
  Item_33=`I make valued contributions to the organization.`,
  Item_34=`I embrace challenging situations at work.`,
 # Item_35=`I speak positively about this organization to others.`,
 # Item_36=`This organization provides the resources necessary for me to successfully perform my job.`
)



Sub_Model_ItemReduction2<-'
Absorption=~Item_1+Item_3+Item_5++Item_8+Item_9+Item_10
Vigor=~Item_13+Item_16+Item_17+Item_18+Item_22+Item_23
Dedication=~Item_26+Item_28+Item_29+Item_32+Item_33+Item_34
'

Fit1.4<-lavaan::cfa(Sub_Model_ItemReduction2, data = Reduction_2Items)
semPlot::semPaths(Fit1.4,"std")
lavaan::fitMeasures(Fit1.4)
summary(Fit1.4, fit.measure=TRUE)

Att_Model_ItemReduction2<-'
Cognitive=~Item_1+Item_3+Item_13+Item_16+Item_26+Item_28
Affective=~Item_5+Item_8+Item_17+Item_18+Item_29+Item_32
Behavioral=~Item_9+Item_10+Item_22+Item_23+Item_33+Item_34
'
Fit1.5<-lavaan::cfa(Att_Model_ItemReduction2, data = Reduction_2Items)
semPlot::semPaths(Fit1.5,"std")
lavaan::fitMeasures(Fit1.5)
summary(Fit1.5, fit.measure=TRUE)


#### Bifactor model 2 items
Bifactor_Model3<-'
Cognitive=~Item_1+Item_3+Item_13+Item_16+Item_26+Item_28
Affective=~Item_5+Item_8+Item_17+Item_18+Item_29+Item_32
Behavioral=~Item_9+Item_10+Item_22+Item_23+Item_33+Item_34
Absorption=~Item_1+Item_3+Item_5++Item_8+Item_9+Item_10
Vigor=~Item_13+Item_16+Item_17+Item_18+Item_22+Item_23
Dedication=~Item_26+Item_28+Item_29+Item_32+Item_33+Item_34
Absorption ~~ 0*Affective
Absorption ~~ 0*Behavioral
Absorption ~~ 0*Cognitive
Vigor ~~ 0*Affective
Vigor ~~ 0*Behavioral
Vigor ~~ 0*Cognitive
Dedication ~~ 0*Affective
Dedication ~~ 0*Behavioral
Dedication ~~ 0*Cognitive
'


Fit.Bi3 <- lavaan::cfa(Bifactor_Model3, data = Reduction_2Items) #, likelihood = "wishart")

semPlot::semPaths(Fit.Bi3, bifactor = c("Cognitive", "Affective", "Behavioral"), "std", layout = "tree3", 
                  rotation = 2, curvePivot=TRUE, style="lisrel", nCharNodes = 0)  ## exoCov=FALSE deletes all covariances
title("Initial pilot bifactor analysis (18 candidate items)")

summary(Fit.Bi3)
```

```{r}
kable(alpha_reduction2[["item.stats"]])
```

# Results

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
